apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels: 
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306 #Por padrao, deixamos a porta 3306 para rodas o banco de dados
      env: #Declarar as variaveis do Banco de dados
        - name: "MYSQL_ROOT_PASSWORD"
          value: "1234567890"
        - name: "MYSQL_DATABASE"
          value: "empresa"
        - name: "MYSQL_PASSWORD"
          value: "123456789"