apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort  #tipo é nodeport
  ports:
    - port: 80
      nodePort: 30000
  selector: #ligar a labels que vai estar no pod
    app: primeiro-pod