apiVersion: apps/v1  # em replica set a versap é essa
kind: Deployment
metadata:
  name: portal-noticias-deployment # Nome do replicaset
spec: # Aqui nós colocamos o template ou seja as especificações do pod
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80 #Onde ele vai escutar se deixar só uma porta ele vai escutar e despachar na msm porta
          envFrom:
            - configMapRef:
                name: portal-configmap
          livenessProbe: # Serve para verificiar se o POd está funcionando, aqui você definee as regras que irá verificar se o Pod está funcionando
            httpGet: #irá fazer uma requisição Get na porta 80
              path: /
              port: 80
            periodSeconds: 10 # Periodo em segundos qeu ele irá verificar 
            failureThreshold: 3 # Quantas falhas eu permito antes de eu executtar o reinicio de um container
            initialDelaySeconds: 20 # Define o tempo de Delay em que ele irá começar dnv os testes
          readinessProbe: # Serve para verificiar se o POd está funcionando, aqui você definee as regras que irá verificar se o Pod está funcionando
            httpGet: #irá fazer uma requisição Get na porta 80
              path: /
              port: 80
            periodSeconds: 10 # Periodo em segundos qeu ele irá verificar 
            failureThreshold: 3 # Quantas falhas eu permito antes de eu executtar o reinicio de um container porem no readiness dps que passar o numero especificado, ele irá mandar as msgs mesmo se n tiver funcionando 
            initialDelaySeconds: 20
          resources: # Aqui nós especificamos quanto de CPU o pod irá usar, nesse caso 10m
            requests:
              cpu: 10m

  replicas: 3 # aqui voce coloca o numero de replicas do pod 
  selector:
    matchLabels:
      app: portal-noticias # Essa label tem que ser igual a o label do pod