apiVersion: storage.k8s.io/v11 # Esse arquvo serve para usar no Google CLoud
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd--standard
  fstype: sxt4
  replication-type: none